defaults:
  # PytorchLightning built-ins
  - learning_rate_monitor_callback
  # NuPlan implemented callbacks
  - model_checkpoint_callback
  - time_logging_callback
  - visualization_callback
  # - closed_loop_callback
  # - raster_closed_loop_training_callback
