_target_: nuplan.planning.training.modeling.closed_loop_utilities.two_stage_training_controller.TwoStageTrainingControllerBatched
_convert_: 'all'

defaults:
  - train_tracker: ilqr_tracker_batched
  - train_motion_model: kinematic_bicycle_model_batched
step_time: 0.5
future_horizon: ${model.future_trajectory_sampling.time_horizon}
